[mgr]
prepend_keymap = [
# re-map W key so can use w
{ on = "W", run = "tasks:show", desc = "Show task manager" },
{ on = ["w", "g"], run = 'shell --orphan -- wezterm cli spawn --cwd "%d" -- lazygit', desc = "Open Lazygit"},
{ on = ["w", "t"], run = 'shell --block -- tig "%h"', desc = "Open Tig"},
{ on = ["w", "v"], run = 'shell --orphan -- wezterm cli spawn -- nvim "%h"', desc = "Open with nvim"},
{ on = ["w", "n"], run = 'shell --orphan -- notepad++.exe "%h"', desc = "Open with Notepad++"},
{ on = ["w", "s"], run = 'shell --orphan -- wezterm cli spawn --cwd .', desc = "Open new WezTerm tab here"},
 
{ on = ["e", "g"], run = 'shell --orphan -- wt -w 0 new-tab -d "%d" -- lazygit', desc = "Open Lazygit"},
{ on = ["e", "t"], run = 'shell --orphan -- wt -w 0 new-tab -d "%d" -- tig "%h"', desc = "Open Tig in new tab"},
{ on = ["e", "v"], run = 'shell -- wt -w 0 new-tab -- nvim %h', desc = "Open with nvim"},
{ on = ["e", "n"], run = 'shell --orphan -- notepad++.exe "%h"', desc = "Open with Notepad++"},
{ on = ["e", "s"], run = 'shell -- wt -w 0 new-tab', desc = "Open pwsh", for = "windows"},

# Plugin Projects
{ on = ["P", "s"], run = "plugin projects save", desc = "Save current project" },
{ on = ["P", "l"], run = "plugin projects load", desc = "Load project" },
{ on = ["P", "P"], run = "plugin projects load_last", desc = "Load last project" },
{ on = ["P", "d"], run = "plugin projects delete", desc = "Delete project" },
{ on = ["P", "D"], run = "plugin projects delete_all", desc = "Delete all projects" },
{ on = ["P", "m"], run = "plugin projects 'merge current'", desc = "Merge current tab to other projects" },
{ on = ["P", "M"], run = "plugin projects 'merge all'", desc = "Merge current project to other projects" },
]

# # F2 + G → lazygit
# [[mgr.prepend_keymap]]
# on = [ "<F2>", "G" ]
# run = 'shell --orphan -- powershell.exe -NoProfile -File "~/.config/yazi/scripts/terminal.ps1" "lazygit" "%d"'
# desc = "Open lazygit in new terminal tab"
#
#
# # F2 + N → nvim
# [[mgr.prepend_keymap]]
# on = [ "<F2>", "N" ]
# run = 'shell --orphan -- powershell.exe -NoProfile -File "~/.config/yazi/scripts/terminal.ps1" "nvim" "%d"'
# desc = "Open nvim in new terminal tab"
