[mgr]
ratio = [ 1, 3, 4 ]
show_hidden = true
show_symlink = true

#[preview]
#max_width = 1200
#max_height = 1200

[opener]
default = [
    { run = 'start "" %s1', orphan = true, for = "windows" },
]

[open]
prepend_rules = [
	# { mime = "*", use = "default" },
]
