source-file ~/.config/tmux/tmux.reset.conf

set -g default-terminal "tmux-256color"
set -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
bind ^A send-prefix
set -g base-index 1              # start indexing windows at 1 instead of 0
#set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 10000     # 1000000, increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"

set -g mouse on

setw -g mode-keys vi
#set -g pane-border-indicators both
# not work with catppuccin
#set -g pane-active-border-style 'fg=magenta,bg=default'
#set -g pane-border-style 'fg=brightblack,bg=default'


#set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
#set -g @fzf-url-history-limit '2000'

### configure Tmux Plugin Manager
set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{HOME}/.local/share/tmux/plugins/'

if 'test ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm"' {
  run 'mkdir -p "${TMUX_PLUGIN_MANAGER_PATH}"'
  run 'git clone https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"'
  run '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'
#set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'tmux-plugins/tmux-continuum'
#set -g @plugin 'fcsonline/tmux-thumbs'
#set -g @plugin 'sainnhe/tmux-fzf'
#set -g @plugin 'wfxr/tmux-fzf-url'
#set -g @plugin 'omerxx/tmux-sessionx'
#set -g @plugin 'omerxx/tmux-floax'
#set -g @floax-width '80%'
#set -g @floax-height '80%'
#set -g @floax-border-color 'magenta'
#set -g @floax-text-color 'blue'
#set -g @floax-bind 'p'
#set -g @floax-change-path 'true'
#set -g @sessionx-bind-zo-new-window 'ctrl-y'
#set -g @sessionx-auto-accept 'off'
#set -g @sessionx-custom-paths '/home/smallcat/.dotfiles'
#set -g @sessionx-bind 'o'
#set -g @sessionx-x-path '~/dotfiles'
#set -g @sessionx-window-height '85%'
#set -g @sessionx-window-width '75%'
#set -g @sessionx-zoxide-mode 'on'
#set -g @sessionx-custom-paths-subdirectories 'false'
#set -g @sessionx-filter-current 'false'
#set -g @continuum-restore 'on'
#set -g @resurrect-strategy-nvim 'session'

### https://github.com/catppuccin/tmux
#set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'left'
#set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_text '#W' #"#{b:pane_current_path}"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
#set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bg=#{@thm_peach}]#{?#{!=:#{window_name},}, #W,}"
#set -g @catppuccin_window_current_text_color "#{@thm_peach}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"

#set -g @catppuccin_pane_status_enabled "yes"
#set -g @catppuccin_pane_border_status "yes"
set -g @catppuccin_pane_active_border_style "##{?pane_in_mode,fg=#{@thm_peach},##{?pane_synchronized,fg=#{@thm_rosewater},fg=#{@thm_peach}}}"
#set -g @catppuccin_pane_color "#{@thm_rosewater}"

# source the plugin
run '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/catppuccin.tmux'
set -g status-left-length 50
set -g status-right-length 50
set -g status-left '#{E:@catppuccin_status_session}'
set -g status-right '#{E:@catppuccin_status_directory}'
#set -ag status-right '#{E:@catppuccin_status_date_time}'

# initialize tmux plugin manager and source all plugins
run '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm'
